Repository AY2223S1-CS2103T-T09-3/tp, pull requests merged in 2022-10, with the labels that each got.

#76 Branch command add staff command
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
Labels: enhancement

#83 Branch update developer and user guide with delete staff command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#84 Branch testing commands
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/DeleteStaffParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/model/staff/UniqueStaffList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/StaffListCard.fxml
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteStaffCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteStaffParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/staff/StaffTest.java
  src/test/java/seedu/address/model/staff/UniqueStaffListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStaffTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/StaffUtil.java
  src/test/java/seedu/address/testutil/TypicalStaff.java
Labels: enhancement

#102 Add Task List
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/staff/Staff.java
  src/main/java/seedu/address/model/staff/exceptions/DuplicateStaffException.java
  src/main/java/seedu/address/model/staff/exceptions/StaffNotFoundException.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDeadline.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalProjectsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/task/TaskDeadlineTest.java
  src/test/java/seedu/address/model/task/TaskDescriptionTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: enhancement, priority.HIGH

#103 Branch command sort project
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/project/Deadline.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement

#105 Update Developer Guide
  docs/DeveloperGuide.md
  docs/images/TaskListUML.png
Labels: documentation

#110 Branch developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteStaffCommandActivityDiagram.puml
  docs/diagrams/MarkAndUnmarkActivityDiagram.puml
  docs/diagrams/MarkCommandSequenceDiagram.puml
  docs/images/DeleteStaffCommandActivityDiagram.png
  docs/images/MarkAndUnmarkActivityDiagram.png
  docs/images/MarkCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
Labels: documentation

#113 Update DG with AddStaffCommand
  docs/DeveloperGuide.md
  docs/images/AddStaffCommandExecution.png
Labels: documentation

#115 Branch delete task
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/model/task/TaskDescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskMark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalProjectsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: enhancement

#117 Link up tasklist to UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: enhancement, priority.HIGH

#120 Branch staff list updates
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StaffListPanel.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidProjectAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalProjectsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
Labels: bug

#122 Branch filter task
  src/main/java/seedu/address/logic/commands/FilterTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/project/ProjectName.java
  src/main/java/seedu/address/model/staff/StaffName.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/model/staff/StaffTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
Labels: enhancement

#124 Branch add find and sort task commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/SortTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
Labels: enhancement, priority.HIGH

#127 Branch mark and unmark tasks
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskParserCommandTest.java
  src/test/java/seedu/address/logic/parser/UnmarkTaskCommandParserTest.java
Labels: enhancement

#128 Branch edit task command
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ProjectUtil.java
  src/test/java/seedu/address/testutil/TaskUtil.java
Labels: enhancement

#129 Change colour scheme
  docs/DeveloperGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/main/java/seedu/address/ui/StaffListPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProjectListPanel.fxml
  src/main/resources/view/StaffListCard.fxml
  src/main/resources/view/StaffListPanel.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: enhancement, priority.MEDIUM

#130 Branch command edit staff command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/model/staff/UniqueStaffList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStaffDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditStaffCommandParserTest.java
  src/test/java/seedu/address/testutil/EditStaffDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StaffUtil.java
Labels: enhancement

#133 Update User Guide
  docs/UserGuide.md
  docs/images/CommandBox.png
  docs/images/ListPanel.png
  docs/images/ResultDisplay.png
  docs/images/helpMessage.png
Labels: documentation

#137 Branch UI messages
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindStaffCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/deadline/Deadline.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/java/seedu/address/ui/StaffCard.java
  src/main/java/seedu/address/ui/StaffListPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStaffCommandTest.java
Labels: enhancement

#136 Branch docs user guide
  docs/UserGuide.md
Labels: documentation

#138 Branch docs user guide
  docs/UserGuide.md
Labels: documentation

#140 Branch bug fixes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindStaffCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteStaffParser.java
  src/main/java/seedu/address/model/deadline/Deadline.java
  src/main/java/seedu/address/model/project/Budget.java
  src/main/java/seedu/address/model/staff/StaffContact.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStaffCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteStaffParserTest.java
  src/test/java/seedu/address/testutil/StaffUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.HIGH

#142 Branch UI
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/FindStaffCommand.java
  src/main/java/seedu/address/model/staff/StaffContact.java
  src/main/java/seedu/address/model/staff/StaffLeave.java
  src/main/java/seedu/address/model/task/TaskMark.java
Labels: documentation

#190 Fix bugs detected from PE dry run
  docs/UserGuide.md
  src/main/java/seedu/address/model/project/Budget.java
  src/main/java/seedu/address/model/staff/StaffContact.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidProjectAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/project/BudgetTest.java
  src/test/java/seedu/address/model/staff/StaffContactTest.java
  src/test/java/seedu/address/model/staff/StaffNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalStaff.java
Labels: bug
