Repository AY2223S1-CS2103T-T09-3/tp, pull requests merged in 2022-11, with the labels that each got.

#191 Branch fix find commands bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FindStaffCommandParser.java
  src/main/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/staff/StaffNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskDescriptionContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindStaffCommandParserTest.java
  src/test/java/seedu/address/model/staff/StaffNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskDescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: bug, documentation

#192 Fix PED issues
  docs/UserGuide.md
  docs/images/CommandBox.png
  docs/images/ProjectPanel.png
  docs/images/ResultDisplay.png
  docs/images/StaffPanel.png
  docs/images/TaskPanel.png
  docs/images/Ui.png
  docs/images/UiLabelled.png
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: bug, documentation

#195 Update JingJie PPP
  docs/team/jjtan444.md
Labels: documentation

#197 Branch ppp max
  docs/UserGuide.md
  docs/images/maxng17.png
  docs/team/maxng17.md
Labels: documentation

#200 Update UG and PPP
  docs/UserGuide.md
  docs/images/augustdespair.png
  docs/team/augustdespair.md
  src/main/java/seedu/address/commons/util/StringUtil.java
Labels: documentation

#208 Branch code quality
  src/main/java/seedu/hrpro/logic/commands/AddStaffCommand.java
  src/main/java/seedu/hrpro/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/hrpro/logic/commands/EditStaffCommand.java
  src/main/java/seedu/hrpro/model/Model.java
  src/main/java/seedu/hrpro/model/ModelManager.java
  src/test/java/seedu/hrpro/logic/commands/AddCommandTest.java
  src/test/java/seedu/hrpro/logic/commands/AddTaskCommandTest.java
Labels: enhancement

#209 Update developer guide with effort appendix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/augustdespair.md
  docs/team/jjtan444.md
  docs/team/maxng17.md
  docs/team/reneeyeow02.md
  src/main/java/seedu/hrpro/logic/parser/DeleteStaffCommandParser.java
  src/main/java/seedu/hrpro/logic/parser/HrProParser.java
  src/test/java/seedu/hrpro/logic/parser/DeleteStaffCommandParserTest.java
Labels: documentation

#212 Branch bug fixes
  docs/UserGuide.md
  src/main/java/seedu/hrpro/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/hrpro/logic/commands/EditStaffCommand.java
  src/main/java/seedu/hrpro/model/Model.java
  src/main/java/seedu/hrpro/model/ModelManager.java
  src/test/java/seedu/hrpro/logic/commands/AddCommandTest.java
  src/test/java/seedu/hrpro/logic/commands/AddTaskCommandTest.java
Labels: bug

#216 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/SortTaskSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/SortTaskSequenceDiagram.png
Labels: documentation

#220 Branch documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/DeleteStaffCommandActivityDiagram.puml
  docs/diagrams/MarkCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteStaffCommandActivityDiagram.png
  docs/images/MarkCommandSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#222 Update Dev guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/AddStaffCommandSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditStaffCommandSequenceDiagram.png
  docs/images/FindStaffCommandSequenceDiagram.png
  docs/images/MarkCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelProjectClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/reneeyeow02.png
  docs/team/reneeyeow02.md
Labels: documentation

#225 Update Dev guide + PPP
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/team/darren12345677.md
  docs/team/reneeyeow02.md
Labels: documentation

#226 Branch test cases
  docs/DeveloperGuide.md
  docs/diagrams/MarkCommandSequenceDiagram.puml
  docs/images/MarkCommandSequenceDiagram.png
  docs/images/SortTaskSequenceDiagram.png
  src/main/java/seedu/hrpro/model/ModelManager.java
  src/main/java/seedu/hrpro/model/project/exceptions/DuplicateProjectException.java
  src/main/java/seedu/hrpro/model/tag/Tag.java
  src/test/java/seedu/hrpro/commons/core/index/IndexTest.java
  src/test/java/seedu/hrpro/model/HrProTest.java
  src/test/java/seedu/hrpro/model/ModelManagerTest.java
  src/test/java/seedu/hrpro/model/UserPrefsTest.java
  src/test/java/seedu/hrpro/model/deadline/DeadlineTest.java
  src/test/java/seedu/hrpro/model/project/BudgetTest.java
  src/test/java/seedu/hrpro/model/project/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/hrpro/model/project/NameTest.java
  src/test/java/seedu/hrpro/model/project/ProjectTest.java
  src/test/java/seedu/hrpro/model/project/UniqueProjectListTest.java
  src/test/java/seedu/hrpro/model/staff/StaffContactTest.java
  src/test/java/seedu/hrpro/model/staff/StaffDepartmentTest.java
  src/test/java/seedu/hrpro/model/staff/StaffLeaveTest.java
  src/test/java/seedu/hrpro/model/staff/StaffNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/hrpro/model/staff/StaffNameTest.java
  src/test/java/seedu/hrpro/model/staff/StaffTest.java
  src/test/java/seedu/hrpro/model/staff/StaffTitleTest.java
  src/test/java/seedu/hrpro/model/staff/UniqueStaffListTest.java
  src/test/java/seedu/hrpro/model/tag/TagTest.java
  src/test/java/seedu/hrpro/model/task/TaskDescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/hrpro/model/task/TaskDescriptionTest.java
  src/test/java/seedu/hrpro/model/task/TaskMarkTest.java
  src/test/java/seedu/hrpro/model/task/TaskTest.java
  src/test/java/seedu/hrpro/model/task/UniqueTaskListTest.java
Labels: testing

#232 Increase code quality
  docs/team/maxng17.md
  src/main/java/seedu/hrpro/logic/commands/EditStaffCommand.java
  src/main/java/seedu/hrpro/model/deadline/Deadline.java
  src/main/java/seedu/hrpro/model/project/Budget.java
  src/main/java/seedu/hrpro/model/project/ProjectName.java
  src/main/java/seedu/hrpro/model/project/ProjectNameContainsKeywordsPredicate.java
  src/main/java/seedu/hrpro/model/staff/StaffContact.java
  src/main/java/seedu/hrpro/model/staff/StaffDepartment.java
  src/main/java/seedu/hrpro/model/staff/StaffLeave.java
  src/main/java/seedu/hrpro/model/staff/StaffName.java
  src/main/java/seedu/hrpro/model/staff/StaffNameContainsKeywordsPredicate.java
  src/main/java/seedu/hrpro/model/staff/StaffTitle.java
  src/main/java/seedu/hrpro/model/tag/Tag.java
  src/main/java/seedu/hrpro/model/task/TaskDescription.java
  src/main/java/seedu/hrpro/model/task/TaskDescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/hrpro/model/task/TaskMark.java
  src/main/java/seedu/hrpro/storage/JsonAdaptedProject.java
  src/main/java/seedu/hrpro/storage/JsonAdaptedStaff.java
  src/main/java/seedu/hrpro/storage/JsonAdaptedTag.java
  src/main/java/seedu/hrpro/storage/JsonAdaptedTask.java
  src/main/java/seedu/hrpro/ui/ProjectCard.java
  src/main/java/seedu/hrpro/ui/StaffCard.java
  src/test/java/seedu/hrpro/logic/commands/CommandTestUtil.java
  src/test/java/seedu/hrpro/logic/parser/HrProParserTest.java
  src/test/java/seedu/hrpro/model/ModelManagerTest.java
  src/test/java/seedu/hrpro/testutil/ProjectUtil.java
  src/test/java/seedu/hrpro/testutil/StaffUtil.java
Labels: priority.HIGH
